"""
Pydantic models for the Health Agent.
Defines data structures for tasks, results, intents, and other domain objects.
"""

from typing import Optional, List, Dict, Any
from datetime import datetime
from pydantic import BaseModel, Field
from enum import Enum


class TimeRangeType(str, Enum):
    """Type of time range specification."""
    ABSOLUTE = "absolute"
    RELATIVE = "relative"


class TimeRange(BaseModel):
    """Time range for analysis queries."""
    range_type: TimeRangeType = TimeRangeType.RELATIVE
    start_date: Optional[datetime] = None
    end_date: Optional[datetime] = None
    last_n_days: Optional[int] = Field(default=30, ge=1, le=365)
    
    def to_query_filter(self) -> Dict[str, Any]:
        """Convert to MongoDB date filter."""
        if self.range_type == TimeRangeType.ABSOLUTE and self.start_date and self.end_date:
            return {
                "$gte": self.start_date,
                "$lte": self.end_date
            }
        elif self.last_n_days:
            from datetime import timedelta
            end = datetime.utcnow()
            start = end - timedelta(days=self.last_n_days)
            return {
                "$gte": start,
                "$lte": end
            }
        return {}


class AnalysisTask(BaseModel):
    """
    Dynamically defined analysis task.
    Generated by the Brief node based on user intent.
    """
    task_id: str = Field(..., description="Unique identifier for the task")
    objective: str = Field(..., description="Natural language description of what to analyze")
    relevant_fields: List[str] = Field(
        default_factory=list,
        description="MongoDB document fields relevant to this analysis"
    )
    time_range: TimeRange = Field(default_factory=TimeRange)
    aggregation_hints: List[str] = Field(
        default_factory=list,
        description="Suggested aggregation types: daily_average, weekly_trend, anomaly_detection, correlation"
    )
    priority: int = Field(default=1, ge=1, le=5, description="Execution priority (1=highest)")
    
    class Config:
        json_schema_extra = {
            "example": {
                "task_id": "t1",
                "objective": "Calculate 7-day rolling average of sleep hours",
                "relevant_fields": ["sleep.asleep_seconds", "sleep.end_time"],
                "time_range": {"range_type": "relative", "last_n_days": 30},
                "aggregation_hints": ["daily_average", "weekly_trend"],
                "priority": 1
            }
        }


class SubAgentResult(BaseModel):
    """Result from a sub-agent analysis task."""
    task_id: str = Field(..., description="ID of the task this result corresponds to")
    objective: str = Field(..., description="The original objective")
    summary: str = Field(..., description="Natural language summary of findings")
    key_metrics: Dict[str, Any] = Field(
        default_factory=dict,
        description="Computed metrics (e.g., {'avg_sleep_hours': 7.2})"
    )
    trends: List[Dict[str, Any]] = Field(
        default_factory=list,
        description="Identified trends over time"
    )
    anomalies: List[Dict[str, Any]] = Field(
        default_factory=list,
        description="Detected anomalies or outliers"
    )
    supporting_data: List[Dict[str, Any]] = Field(
        default_factory=list,
        description="Raw data points supporting the analysis"
    )
    caveats: List[str] = Field(
        default_factory=list,
        description="Data quality issues, missing data, limitations"
    )
    success: bool = Field(default=True, description="Whether the analysis succeeded")
    error: Optional[str] = Field(default=None, description="Error message if failed")


class ClarifiedIntent(BaseModel):
    """Structured representation of the user's clarified health query intent."""
    original_query: str = Field(..., description="The user's original question")
    health_domains: List[str] = Field(
        default_factory=list,
        description="Health areas: sleep, activity, heart, nutrition, etc."
    )
    specific_metrics: List[str] = Field(
        default_factory=list,
        description="Specific metrics requested: steps, HRV, sleep_hours, etc."
    )
    time_context: TimeRange = Field(default_factory=TimeRange)
    comparison_requested: bool = Field(
        default=False,
        description="Whether user wants to compare periods/metrics"
    )
    comparison_details: Optional[str] = Field(
        default=None,
        description="Details about what to compare"
    )
    goal_context: Optional[str] = Field(
        default=None,
        description="User's health goal context if mentioned"
    )
    clarification_complete: bool = Field(
        default=False,
        description="Whether enough info gathered to proceed"
    )
    clarification_questions: List[str] = Field(
        default_factory=list,
        description="Questions still needed for clarification"
    )


class AggregatedInsights(BaseModel):
    """Aggregated insights from all sub-agent results."""
    summary: str = Field(..., description="Overall summary of all findings")
    cross_metric_patterns: List[Dict[str, Any]] = Field(
        default_factory=list,
        description="Patterns found across different metrics"
    )
    correlations: List[Dict[str, Any]] = Field(
        default_factory=list,
        description="Correlations between metrics"
    )
    key_findings: List[str] = Field(
        default_factory=list,
        description="Most important findings to highlight"
    )
    data_quality_notes: List[str] = Field(
        default_factory=list,
        description="Overall data quality observations"
    )
    recommendations_context: List[str] = Field(
        default_factory=list,
        description="Context for potential lifestyle considerations (non-prescriptive)"
    )


class HealthReport(BaseModel):
    """Final health report generated for the user."""
    title: str = Field(..., description="Report title")
    generated_at: datetime = Field(default_factory=datetime.utcnow)
    executive_summary: str = Field(..., description="Brief overview of findings")
    detailed_findings: List[Dict[str, Any]] = Field(
        default_factory=list,
        description="Detailed analysis sections"
    )
    visualizations_data: List[Dict[str, Any]] = Field(
        default_factory=list,
        description="Data formatted for charts/visualizations"
    )
    caveats_and_limitations: List[str] = Field(
        default_factory=list,
        description="Important disclaimers and data limitations"
    )
    suggested_next_queries: List[str] = Field(
        default_factory=list,
        description="Follow-up questions the user might want to explore"
    )
